#application.name=Sistema de Localizacao
## DATASOURCE
#spring.datasource.url=jdbc:h2:mem:db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
## JPA
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console