#spring.profiles.active=test
#server.port=8081
#server.servlet.context-path=/sistema-localizacao


spring:
  profiles:
    active: "test"
server:
  port: 8081
  servlet:
    context-path: /sistema-localizacao
